FROM alpine:latest AS certificates
RUN apk add --no-cache ca-certificates

FROM scratch
WORKDIR /app
COPY --from=certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY .runtime/vohive /app/vohive
ENTRYPOINT ["/app/vohive"]
